### ISSUE TITLE
Mermaid-Fixer does not work on Export to PDF

### ISSUE THREAD

**Issue by florencekl** [Bunker-D/mermaid-fixer#1]
## Expected Behavior

Mermaid Arrows/Marks show up in PDF when exporting from Markdown to PDF with Mermaid Fixer

## Actual Behavior

While the fix applies in Viewing and Editing Mode as soon as you Export a file to PDF the arrows/marks are gone again

## Steps to Reproduce the Problem

  1. Create new file
  2. Add at least 2 different Graphs which share node-names:
      ```mermaid
      graph LR
      A --> B
      ```
       
      ```mermaid
      graph LR
      A --> C
      ```
  3. Export to PDF with standard obsidian settings
  
   ![image](https://github.com/Bunker-D/obsidian-mermaid-fixer/assets/59734957/e85e7364-aa78-4266-bb0f-3012ed9c6a45)

**Comment by Bunker-D** [comment]
Unfortunately, the was this extension works cannot affect exported PDF.

However, when I [proposed](https://github.com/obsidianmd/obsidian-releases/pull/2061#issuecomment-1603480615) some modifications to Obsidian's source code that should solve the issues my plugin addresses in a cleaner way, without the plugin. Hopefully, it will also solve the issue with PDFs.

The change has already been included into the [v.1.4.0 update for Obsidian Catalyst](https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0/) (the paid early-access version of Obsidian), and should arrive later in the public version. I have no access to the Catalyst version, so I cannot check the results and whether or not they translate to PDF exports.

**Comment by florencekl** [comment]
Thank you very much, great to hear that your fix is included in the next update (it is vital in my opinion).
